### PR TITLE
hide video, change how it works texts

### PR DESCRIPTION
**Pull request by zazoley**

### CODE REVIEW

**Comment by fosils** [comment]
What is the link to test this? I have forgotten

**Comment by fosils** [comment]
Did you get this task from Tamir?

**Comment by Trex182** [comment]
Yes, I asked for this. And I have already checked the work on a test server.

Tamir

**Comment by zazoley** [comment]
The link is http://dk.jobexp.ru/

**Comment by fosils** [comment]
I have deployed to eBogholderen.dk now

**Comment by fosils** [comment]
@Trex182 I think these changes are just excellent! I love them!

**Pull request merged**
